### ISSUE TITLE
Seeed XIAO BLE NFC pins.

### ISSUE THREAD

**Issue by azhizhinov** [idesignstuff/zmk-config#3]
Hello, good fellow.
I've used you [schema](https://github.com/idesignstuff/narsil3.2/blob/master/image/2023-07-19%2022_59_53-narsil_2023-06-24_18-00-45%20_%20narsil_schematic.narsil%20_%20EasyEDA%20Pro%20-%20V2.0.30.0bf.png) and code to realize something similar, but can't get the ROW0 and ROW1 to work.
Is there are some additional steps needed to enable those pins to work with the ZMK firmware?
Could you, please, help?

**Comment by idesignstuff** [comment]
In your [shield].conf file, add:


`
#Uncomment below to enable NFC pins for gpio0 9 and gpio0 10
CONFIG_NFCT_PINS_AS_GPIOS=y
`

And then you can assign those pins in your dtsi file for matrix
rows/columns as usual.

Christian

**Comment by idesignstuff** [comment]
Question answered

**Comment by azhizhinov** [comment]
Hello.
Wow, that simple.
I'll try.
Thanks a lot.
